name: Process issue
on:
  issues:
    types: opened
      - labeled

concurrency: 'main'

jobs:
  parse_issue:
    if: startsWith(github.event.label.name, 'parse')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new_form.yaml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: JSON to YAML
        uses: NeddM/JSON-to-YAML@v1
        with:
          input: issue.json
          output: parsed_issue.yaml

      - run: cat parsed_issue.yaml
