name: Process issue
on:
  issues:
    types: opened

concurrency: 'main'

jobs:
  place_order:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new_form.yml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - run: cat issue.json
