name: Process issue
on:
  issues:
    types:
      - labeled

jobs:
  parse_issue:
    if: startsWith(github.event.label.name, 'parse')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: stefanbuck/github-issue-praser@v3
        id: issue-parser
        with:
          template-path: .github/ISSUE_TEMPLATE/new_form.yaml

      - run: echo '${{ steps.issue-parser.outputs.jsonString }}' > issue.json

      - name: JSON to YAML
        uses: NeddM/JSON-to-YAML@v1
        with:
          input: issue.json
          output: parsed_issue.yaml

      - name: Upload generated YAML as artifact
        uses: actions/upload-artifact@v4
        with:
          name: parsed_issue
          path: parsed_issue.yaml

  merge_issue:
    if: startsWith(github.event.label.name, 'merge')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4

      - run: ls -la
