# .github/workflows/push-artifact.yml
name: Push Artifact

on:
  workflow_dispatch:
    inputs:
      run:
        description: 'Run-id number associated with the artifact'
        required: true
      file_name:
        description: 'Name to assign to the yaml service file'
        required: true
      git_email:
        description: 'Email associated with your GitHub accout'
        required: true
      git_user:
        description: 'Username associated with your GitHub accout'
        required: true

jobs:
  push_artifact:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          github-token: ${{ secrets.GIT_TOKEN }}
          run-id: ${{ github.event.inputs.run }}

      - name: List artifact directory
        run: ls -la parsed_issue

      - name: Add artifact
        run: |
          mv parsed_issue/parsed_issue.yaml appliances/service/${{ github.event.inputs.file_name }}
          git add appliances/service/${{ github.event.inputs.file_name }}
          
      - name : Push artifact
        run: |
          git config --local user.email "your_email@example.com"
          git config --local user.name "Your Name"
          git commit -m "Add YAML generated by run #${{ github.event.inputs.run }}"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
